services:
  db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: data
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345687
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: dev
      PMA_PASSWORD: 12345687
    ports:
      - "8080:80"
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  db_data:
